import User from '../models/User.js';
import bcrypt from 'bcryptjs';
import { ApiError } from '../middleware/errorMiddleware.js';
import { escapeRegExp, safeString } from '../utils/querySafety.js';
import { getWorkspaceId, requestScope } from '../utils/tenancy.js';

/**
 * Admin Operator Management — real backend-backed user CRUD.
 *
 * Only admins can manage operators. Handlers are read-only.
 * Password hashes are NEVER exposed.
 *
 * Phase 21 — this surface enforces the SAME matrix as staffController:
 *   any admin may manage HANDLER accounts; only the OWNER (role admin +
 *   isOwner) may act on ADMINISTRATOR/owner accounts (create, promote,
 *   suspend, demote, delete). Self-action stays refused (422) first.
 */

/** Owner-gate mirror of staffController.assertCanManage (minus self/fixture). */
function assertOwnerMayManageAdministrator(req, target) {
  const actorIsOwner = req.user.role === 'admin' && !!req.user.isOwner;
  if (target.role === 'admin' && !actorIsOwner) {
    throw new ApiError(403, 'Only the owner can manage administrator accounts.', 'OWNER_REQUIRED');
  }
}

export async function listOperators(req, res, next) {
  try {
    const { role, status } = req.query;
    const q = safeString(req.query.q, 200);
    const match = { role: { $in: ['admin', 'handler'] } };
    if (role && role !== 'ALL') {
      match.role = role === 'ADMINISTRATOR' ? 'admin' : 'handler';
    }
    if (q) {
      const regex = new RegExp(escapeRegExp(q), 'i');
      match.$or = [{ name: regex }, { email: regex }];
    }
    // Operators are members: the owner (platform scope) sees every account,
    // a workspace's admins see only their own workspace plus legacy rows.
    const users = await User.find({ ...requestScope(req), ...match })
      .select('-passwordHash')
      .sort({ createdAt: -1 })
      .limit(200);
    // Map to the frontend shape
    const operators = users.map((u) => ({
      id: u._id.toString(),
      name: u.name || u.email.split('@')[0],
      initials: (u.name || u.email)
        .split(' ')
        .map((w) => w[0])
        .join('')
        .toUpperCase()
        .slice(0, 2),
      title: u.role === 'admin' ? 'Administrator' : 'Handler',
      role: u.role === 'admin' ? 'ADMINISTRATOR' : 'HANDLER',
      email: u.email,
      status: u.status || 'ACTIVE',
      lastActivity: u.updatedAt
        ? formatRelativeTime(u.updatedAt)
        : 'Unknown',
      isFixture: !!u.isFixture,
      createdAt: u.createdAt,
    }));
    res.json({ success: true, operators });
  } catch (err) {
    next(err);
  }
}

export async function createOperator(req, res, next) {
  try {
    const { name, email, role, password } = req.body;
    if (!name || !email) {
      throw new ApiError(422, 'Name and email are required.', 'VALIDATION_ERROR');
    }
    // Duplicate check comes FIRST: an existing email must answer 409 no
    // matter what else is missing from the request.
    const existing = await User.findOne({
      // Deliberately global (NOT workspaceId-scoped): an address identifies
      // ONE account platform-wide, so a second workspace cannot reuse it.
      email: email.toLowerCase(),
    });
    if (existing) {
      throw new ApiError(409, 'A user with this email already exists.', 'DUPLICATE');
    }
    // Phase 20.6.1 — the role must be an explicit staff role. The previous
    // mapping silently turned ANY unrecognized value (including 'customer'
    // or garbage) into a handler; unknown roles are now rejected.
    const ROLE_MAP = { admin: 'admin', handler: 'handler', ADMINISTRATOR: 'admin', HANDLER: 'handler' };
    const userRole = ROLE_MAP[role];
    if (!userRole) {
      throw new ApiError(422, 'Role must be admin or handler.', 'VALIDATION_ERROR');
    }
    // Phase 21 — minting an administrator is an owner-only privilege on every
    // surface (staff invitations fix the role to handler for the same reason);
    // without this a non-owner admin could bypass the owner matrix by simply
    // creating a fresh admin account.
    if (userRole === 'admin') {
      assertOwnerMayManageAdministrator(req, { role: 'admin' });
    }
    // Phase 20.6.1 — passwords are REQUIRED (the caller sets an initial
    // password out-of-band) and are never generated by or returned from the
    // API. Same minimum as public registration: 6 characters. Hashed with
    // the existing bcrypt-12 scheme; plaintext never stored or echoed.
    if (!password || String(password).length < 6) {
      throw new ApiError(422, 'Password must be at least 6 characters.', 'VALIDATION_ERROR');
    }
    const passwordHash = await bcrypt.hash(String(password), 12);
    // Server-derived membership: an operator minted by a workspace admin joins
    // THAT workspace; the owner mints platform identities (no workspaceId).
    const operatorWorkspaceId = getWorkspaceId(req.user);
    const user = await User.create({
      email: email.toLowerCase(),
      passwordHash,
      role: userRole,
      name: name.trim(),
      isFixture: false,
      ...(operatorWorkspaceId ? { workspaceId: operatorWorkspaceId } : {}),
    });
    const operator = {
      id: user._id.toString(),
      name: user.name,
      initials: user.name
        .split(' ')
        .map((w) => w[0])
        .join('')
        .toUpperCase()
        .slice(0, 2),
      title: userRole === 'admin' ? 'Administrator' : 'Handler',
      role: userRole === 'admin' ? 'ADMINISTRATOR' : 'HANDLER',
      email: user.email,
      status: 'ACTIVE',
      lastActivity: 'Just now',
      isFixture: false,
      createdAt: user.createdAt,
    };
    // Phase 20.6.1 — NO credential material in the response, ever. The
    // password arrived in the request body over TLS and exists in the DB only
    // as a bcrypt hash; it is not echoed here (it previously was, as a
    // one-time `tempPassword`, which also put it at risk of landing in logs).
    res.status(201).json({
      success: true,
      operator,
    });
  } catch (err) {
    next(err);
  }
}

/**
 * PATCH /api/admin/users/:id/status — suspend or reactivate an operator.
 *
 * Suspension is enforced server-side: login rejects suspended accounts and
 * every protected request re-checks status from the database, so an existing
 * token stops working immediately.
 */
export async function updateOperatorStatus(req, res, next) {
  try {
    const user = await User.findOne({
      _id: req.params.id,
      ...requestScope(req),
    });
    if (!user) {
      throw new ApiError(404, 'Operator not found.', 'NOT_FOUND');
    }
    if (user._id.toString() === req.user._id.toString()) {
      throw new ApiError(422, 'You cannot change your own account status.', 'VALIDATION_ERROR');
    }
    // Phase 21 — administrators (incl. the owner) are owner-managed only.
    assertOwnerMayManageAdministrator(req, user);
    const { status } = req.body || {};
    if (!['ACTIVE', 'SUSPENDED'].includes(status)) {
      throw new ApiError(422, 'Status must be ACTIVE or SUSPENDED.', 'VALIDATION_ERROR');
    }
    // Guard: never disable the last active administrator.
    if (user.role === 'admin' && status === 'SUSPENDED') {
      const activeAdmins = await User.countDocuments({
        // Deliberately GLOBAL (not workspaceId-scoped): this guard protects
        // the platform from an administration lockout; self-action is already
        // refused above, so scoping it could only weaken the check.
        role: 'admin',
        status: 'ACTIVE',
      });
      if (activeAdmins <= 1) {
        throw new ApiError(422, 'Cannot suspend the last active administrator.', 'VALIDATION_ERROR');
      }
    }
    user.status = status;
    user.statusChangedAt = new Date();
    await user.save();
    res.json({
      success: true,
      operator: {
        id: user._id.toString(),
        name: user.name,
        status: user.status,
      },
    });
  } catch (err) {
    next(err);
  }
}

export async function updateOperatorRole(req, res, next) {
  try {
    const user = await User.findOne({
      _id: req.params.id,
      ...requestScope(req),
    });
    if (!user) {
      throw new ApiError(404, 'Operator not found.', 'NOT_FOUND');
    }
    if (user._id.toString() === req.user._id.toString()) {
      throw new ApiError(422, 'Cannot change your own role.', 'VALIDATION_ERROR');
    }
    const { role } = req.body;
    if (!['admin', 'handler'].includes(role)) {
      throw new ApiError(422, 'Role must be admin or handler.', 'VALIDATION_ERROR');
    }
    // Phase 21 — role assignment touches the administrator cohort from EITHER
    // side: demoting an admin AND promoting a handler into admin are both
    // owner-only (a non-owner promoting an ally would bypass the matrix).
    if (user.role === 'admin' || role === 'admin') {
      assertOwnerMayManageAdministrator(req, user.role === 'admin' ? user : { role: 'admin' });
    }
    // Guard: demoting the last active admin would lock out administration.
    if (user.role === 'admin' && role !== 'admin') {
      const activeAdmins = await User.countDocuments({
        // Deliberately GLOBAL (not workspaceId-scoped): the last-admin rule is
        // a platform-wide safety net, not a per-workspace preference.
        role: 'admin',
        status: 'ACTIVE',
      });
      if (activeAdmins <= 1) {
        throw new ApiError(422, 'Cannot demote the last active administrator.', 'VALIDATION_ERROR');
      }
    }
    user.role = role;
    await user.save();
    res.json({
      success: true,
      operator: {
        id: user._id.toString(),
        name: user.name,
        role: user.role === 'admin' ? 'ADMINISTRATOR' : 'HANDLER',
      },
    });
  } catch (err) {
    next(err);
  }
}

export async function deleteOperator(req, res, next) {
  try {
    const user = await User.findOne({
      _id: req.params.id,
      ...requestScope(req),
    });
    if (!user) {
      throw new ApiError(404, 'Operator not found.', 'NOT_FOUND');
    }
    if (user._id.toString() === req.user._id.toString()) {
      throw new ApiError(422, 'Cannot delete your own account.', 'VALIDATION_ERROR');
    }
    // Phase 21 — deleting an administrator (incl. the owner) is owner-only.
    assertOwnerMayManageAdministrator(req, user);
    if (user.isFixture) {
      throw new ApiError(422, 'Cannot delete seed fixture accounts.', 'VALIDATION_ERROR');
    }
    // Guard: never remove the last active administrator (docs/API promise).
    // Same formula as the suspend/demote guards: the count is of ACTIVE
    // administrators, so a sole-active-admin state can never be written away.
    if (user.role === 'admin') {
      const activeAdmins = await User.countDocuments({
        // Deliberately GLOBAL (not workspaceId-scoped): platform-wide safety
        // net for the last-admin invariant (see updateOperatorStatus).
        role: 'admin',
        status: 'ACTIVE',
      });
      if (activeAdmins <= 1) {
        throw new ApiError(422, 'Cannot delete the last active administrator.', 'VALIDATION_ERROR');
      }
    }
    // Scope re-asserted at write time (TOCTOU-safe), not just on the fetch.
    await User.deleteOne({ _id: user._id, ...requestScope(req) });
    res.json({ success: true, message: `Removed operator "${user.name}".` });
  } catch (err) {
    next(err);
  }
}

function formatRelativeTime(date) {
  const diff = Date.now() - new Date(date).getTime();
  const mins = Math.floor(diff / 60000);
  if (mins < 1) return 'Just now';
  if (mins < 60) return `${mins}m ago`;
  const hours = Math.floor(mins / 60);
  if (hours < 24) return `${hours}h ago`;
  const days = Math.floor(hours / 24);
  if (days < 7) return `${days}d ago`;
  return new Date(date).toLocaleDateString('en-IN');
}
